export function getElements(documentRef = document) {
  return {
    title: documentRef.getElementById("game-title"),
    viewTabs: documentRef.getElementById("view-tabs"),
    areaPanel: documentRef.getElementById("area-panel"),
    areaTitle: documentRef.getElementById("area-title"),
    areaGoal: documentRef.getElementById("area-goal"),
    localStats: documentRef.getElementById("local-stats"),
    manualActions: documentRef.getElementById("manual-actions"),
    statusLine: documentRef.getElementById("status-line"),
    playGrid: documentRef.getElementById("play-grid"),
    districtHint: documentRef.getElementById("district-hint"),
    buildingsList: documentRef.getElementById("buildings-list"),
    activePoliciesPanel: documentRef.getElementById("active-policies-panel"),
    activePoliciesList: documentRef.getElementById("active-policies-list"),
    policiesPanel: documentRef.getElementById("policies-panel"),
    policyTrees: documentRef.getElementById("policy-trees"),
    annexPanel: documentRef.getElementById("annex-panel"),
    annexationSummary: documentRef.getElementById("annexation-summary"),
    annexButton: documentRef.getElementById("annex-button"),
    encyclopediaPanel: documentRef.getElementById("encyclopedia-panel"),
    codexKindFilter: documentRef.getElementById("codex-kind-filter"),
    codexAreaFilter: documentRef.getElementById("codex-area-filter"),
    codexFamilyFilter: documentRef.getElementById("codex-family-filter"),
    codexCategoryFilter: documentRef.getElementById("codex-category-filter"),
    codexProgressFilter: documentRef.getElementById("codex-progress-filter"),
    codexSummary: documentRef.getElementById("codex-summary"),
    codexList: documentRef.getElementById("codex-list"),
    saveButton: documentRef.getElementById("save-button"),
    exportButton: documentRef.getElementById("export-button"),
    importButton: documentRef.getElementById("import-button"),
    importInput: documentRef.getElementById("import-input"),
    resetButton: documentRef.getElementById("reset-button")
  };
}
